### ISSUE TITLE
Doesn't apply to events that are in my and a friend's calendar

### ISSUE THREAD

**Issue by gausie** [imightbeamy/gcal-multical-event-merge#12]
So for example, if I create an event and invite a friend who has shared their calendar with me, the events are not merged and instead show side-by-side.

The extension still works, however, if I own both calendars.

**Comment by gausie** [comment]
Hmm, seems to be working for some but not others.

**Comment by imightbeamy** [comment]
Hi @gausie, Thanks for letting me know about this issue. I think I've seen this happen when one person responds "maybe" to an event.

Could you take a screenshot of the ones that are and aren't working for you? If you have time, it'd be great to get shots with the extension on and off, but if you're in a hurry just with the extension turn on is fine. 

Thanks!

**Comment by gausie** [comment]
No problem!

***With extension enabled***
<img width="822" alt="screen shot 2015-11-16 at 18 03 12" src="https://cloud.githubusercontent.com/assets/179758/11190285/ac16a9a2-8c8c-11e5-8dce-c4a9414ec8b9.png">
<img width="1024" alt="screen shot 2015-11-16 at 18 01 59" src="https://cloud.githubusercontent.com/assets/179758/11190286/ac1c776a-8c8c-11e5-8cd5-7bf7aa90b86e.png">

***With extension disabled***
<img width="822" alt="screen shot 2015-11-16 at 18 03 29" src="https://cloud.githubusercontent.com/assets/179758/11190283/ac0c3c88-8c8c-11e5-9b91-995c31e04e1d.png">
<img width="1008" alt="screen shot 2015-11-16 at 18 02 49" src="https://cloud.githubusercontent.com/assets/179758/11190284/ac15e3b4-8c8c-11e5-9a63-afcccb0d633a.png">

**Comment by imightbeamy** [comment]
Ahh, it looks like you have the lab feature "Who's my one-on-one with?" enabled. That lab unfortunately breaks the extension because it makes the event names different for the different calendars. To get these to combine, you'll have to disable that lab.

**Comment by gausie** [comment]
Ahha! I'll disable for now. Thanks for your amazing work!

**Comment by gausie** [comment]
That fixed it!

**Comment by imightbeamy** [comment]
Awesome! :smile:
