### ISSUE TITLE
Merged events hide other merged events with different titles when these titles contain unicode only text

### ISSUE THREAD

**Issue by Shtutnik** [imightbeamy/gcal-multical-event-merge#24]
When events titles contain unicode text only, it gets trimmed down to an empty string because of this regex in cleanEventTitle function: 
.replace(/\W/g, ''); // Remove non-ascii chars 

This makes the key of these events to be the same, hence, hiding other events that also contain only unicode text in their titles. 
This is mainly noticed on daily events.

**Comment by ericbimpex** [comment]
If the goal was to filter cake emoji's, wouldn't this be less heavy-handed?
`str.replace(/🎂/g, '').replace(/🍰/g, '')`

**Comment by Shtutnik** [comment]
Hi @ericbimpex ,

I guess that you are correct, since the regex was introduced just for that cake issue. Maybe @imightbeamy wanted to cover other stuff while she was at it?
The fix I proposed should fix it and still give what @imightbeamy was aiming at though it might introduce other problems in the future. 
Your fix would be more exact and maybe it is the one that should be taken.

**Comment by tonibony** [comment]
Hi! I am experiencing the same problem - events with descriptions mostly in non-ASCII characters are merged. Is there a patched version of the Chrome extension that I can try?
