### ISSUE TITLE
Merging of events in monthly view

### ISSUE THREAD

**Issue by mdahlstrand** [imightbeamy/gcal-multical-event-merge#3]
The plugin works perfectly in the 1 day, week, and 4 day views, but unfortunately not in the monthly view. Personally I use the month view most of the time and would really appreciate if it would work in there too.

**Comment by imightbeamy** [comment]
Non-all-day events will now look like this in the month view:
![screenshot 2015-03-12 22 24 23](https://cloud.githubusercontent.com/assets/1229145/6632152/d9cb079c-c907-11e4-987a-577b85caebd1.png)

Chrome store update coming soon.

**Comment by matkinsopcvaus** [comment]
Toggle is working for me in weekly, 4 day, daily, and agenda view, but not in monthly view.
