### ISSUE TITLE
Events with unicode title are hidden in month view

### ISSUE THREAD

**Issue by Shtutnik** [imightbeamy/gcal-multical-event-merge#34]
In month view, on a day that contains events with unicode title, the merged events gets hidden completely. This also happens inside the popup window when clicking +more.
This happens since the event is wrapped inside a table, probably for reversing the text (maybe only happens in rtl languages?) since the table name is te-rev.

**Comment by imightbeamy** [comment]
Hi @sharkoz, could on email at me please? (hi@amy.tech) I'd love to chat about the many pull request you've sent.

**Comment by imightbeamy** [comment]
Also, I'm not seeing this issue, do you mean events with only emoji titles? Could you include a screenshot of the issue?

**Comment by Shtutnik** [comment]
Hi,
So, I checked this out some more and it turns out that this only happens on RTL languages. It seems that the "rev" in the "te-rev" class name is probably for "reverse". 
You can go ahead and add an event with a title containing an RTL language string. If you then inspect the event in month view, you will see that it is wrapped in the aforementioned table. This will cause the event (when merged) to disappear in month view. 
You can analyse my pull request #35 to understand how I dealt with this issue.
