### ISSUE TITLE
Merged event is too wide

### ISSUE THREAD

**Issue by Shtutnik** [imightbeamy/gcal-multical-event-merge#37]
The merged event's width is 100%, where it actually should be smaller in some cases. 
For example, when other events overlap with another event, the overlapping event is a bit smaller. When using the extension on the other hand, the merged event's width gets to 100%. 
This is problematic when there is a merged event which is taking most of the day (say, 08am-17pm) and it overlaps other events, the result is a bit messy, unlike the default behavior without the extension.

**Comment by imightbeamy** [comment]
It spans from the original left edge fully to the right side, which was mostly a quick and dirty solution. I haven't found many cases when this was a huge problem, and I haven't heard other complaints about it. Could you include a screenshot of a situation when this was a problem?

**Comment by Shtutnik** [comment]
Hi,
I agree that this doesn't happen a lot, but given the scenario I wrote above (an event that takes up several hours and overlaps other events) you are left with a very narrow area on the right for creating new events.
Without using the extension, in this scenario, you would have more than half of the screen available for creating new events. 
It's not that of an issue but rather just doesn't look good and has a minor impact on usability, that's all. In my opinion it's best to leave things the way google intended it to be and not to change behavior too much.

Here is a screenshot as an example:
![image](https://cloud.githubusercontent.com/assets/11493106/15385435/460ee778-1daa-11e6-8653-ca101fd649bb.png)

As apposed to:
![image](https://cloud.githubusercontent.com/assets/11493106/15385461/6bf2057e-1daa-11e6-99c3-2625e999a3fb.png)
