### ISSUE TITLE
Publish for Firefox

### ISSUE THREAD

**Issue by robinwhittleton** [imightbeamy/gcal-multical-event-merge#44]
As of Firefox 48, Chrome extensions are supported with minimal if any modifications. I followed [Mozilla’s ‘first extension’ guide](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_first_WebExtension) and loaded gcal-multical-event-merge into my Firefox Nightly and it seems to work as expected. Can this be published on [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/)?

**Comment by metavida** [comment]
FWIW, I was able to install and use this extension with *no* modifications, currently in the general-release Firefox 55.0. Here are the steps I took:

1. Get the code (either by [downloading the zip in your browser](https://github.com/imightbeamy/gcal-multical-event-merge/archive/master.zip) or via `git clone https://github.com/imightbeamy/gcal-multical-event-merge.git` )
2. Follow the Firefox [Temporary installation in Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox) instructions, selecting the `manifest.json` file that you downloaded in step 1.
3. Enjoy! <br> ![multical event merge in ff](https://user-images.githubusercontent.com/1933/30220949-56beb99c-9476-11e7-9a51-213d14ac8c37.png)

**Comment by imightbeamy** [comment]
This is uploaded as a FireFox Add-on now! 
https://addons.mozilla.org/en-US/firefox/addon/google-cal-event-merge/
