### ISSUE TITLE
Events get super narrow

### ISSUE THREAD

**Issue by unn** [imightbeamy/gcal-multical-event-merge#5]
First of all, this extension is brilliant. Thank you so much for your hard work on it.  I don't want to go as far as saying this is a life changer, but it definitely makes my calendar a hell a lot more manageable.

That out of the way, I've noticed when a bunch of my coworkers calendars are visible and meetings overlap both with shared events and non shared that the event will sometimes get super narrow, to the point where I can't even read the text.

![screen shot 2014-07-25 at 9 46 37 am](https://cloud.githubusercontent.com/assets/78317/3702797/20ba786e-1403-11e4-8479-84f4fa76b532.png)

This doesn't happen all the time, if I add another coworker who shares the event, it will expand back open as it adds their calendars stripe to the event.

This is in Chrome 36.0.1985.125 on OS X 10.9.4.

**Comment by kajsaleah** [comment]
Having the same issue.  Viewing anywhere from 5 to 12 calendars.  

The events affected in the below are merged from 2 or 3 calendars, (all part of my organization - added via email).
 
Before:
![before](https://cloud.githubusercontent.com/assets/824895/6626734/3fff7964-c8b6-11e4-94e9-b35d265897d4.jpg)
After:
![after](https://cloud.githubusercontent.com/assets/824895/6626740/4a3097d8-c8b6-11e4-8e4f-97863af3166c.jpg)

**Comment by imightbeamy** [comment]
Thanks for the report @kajsaleah!

**Comment by imightbeamy** [comment]
Thank you all for reporting this bug, I just published the fixed version to the web store. You should get the update in a few hours. Let me know if you still see any teeny tiny events!

**Comment by kajsaleah** [comment]
Wow, thank you so much for being so on top of it.

This is a seriously badass extension.

Have you looked into getting it included in Google's labs? If not, you
should. This is the kind of thing they look for.
