### ISSUE TITLE
Doesn't support New Calendar UI

### ISSUE THREAD

**Issue by ankushg** [imightbeamy/gcal-multical-event-merge#50]
Looks like Google is rolling out a [new Google Calendar UI](https://gsuiteupdates.googleblog.com/2017/10/new-calendar-user-interface17.html).

From what I can tell, the new UI doesn't play nice with this extension/userscript :(

**Comment by imightbeamy** [comment]
I'm sure it doesn't 😞  This is need a big upgrade!

**Comment by ankushg** [comment]
Haha yeah no pressure, I just figured I'd file an issue in case anyone else came here and wondered if it supported the new UI :)

**Comment by imightbeamy** [comment]
Totally, thanks! I'd like it too support it of course :)

**Comment by jacobboon** [comment]
Thats indeed exactly why I came here! I really love your extension so I immediately wondered if you'd looked at this. 😄 

I took a look at the new DOM structure myself and I couldn't really make heads or tails of it... Only thing I'm certain of is that it will not be as straightforward as selecting all `dl` nodes or something similar I think... :(

**Comment by gabro** [comment]
I noticed, but there's a good news! There's now a preference for ticking the option by default under Settings > Event

**Comment by fredley** [comment]
I have no idea how robust this approach is, but finding the calendar DOM elements by attribute seems to work:
```
document.querySelectorAll("[data-dragsource-type='5']")
```

**Comment by morkro** [comment]
Some more findings:
- the `key=""` and `data-eventid=""` properties of duplicated events are _almost_ the same. It's a 54 characters long string and the first 32 characters are always equal.
- `data-dragsource-type=""` are not the same for me, as @fredley has posted above.

In worst case, comparing the `innerHTML` of all elements inside a `role="gridcell"`?

**Comment by cfairbanks** [comment]
That's interesting re data-dragsource-type values.

For me, they seem to consistently be:
2 - event, with times, weekly view, on my main calendar
5 - event, with times, weekly view, on a secondary calendar
6 - event, all-day, weekly view, on my main calendar
9 - event, all-day, weekly view, on a secondary calendar

I haven't dug down further into other scenarios, though.

**Comment by tdudek** [comment]
I've scribbled a first draft which works for the weekly view. Adjusting the width of the merged event needs to be reworked.
Try by copy & paste into the console:

```javascript
var stripesGradient = (colors) => {
  var gradient = "repeating-linear-gradient( 45deg,"
  var pos = 0

  colors.forEach(color => {
    gradient += color + " " + pos + "px,"
    pos += 10
    gradient += color + " " + pos + "px,"
  })
  gradient = gradient.slice(0, -1)
  gradient += ")"
  return gradient
}

// find main calender
var grids = document.querySelectorAll('[role="main"] [role="grid"] > [role="presentation"]')
var mainCalender = Array.from(grids).find(grid => typeof grid.dataset.isColumnViewContext === 'undefined')

// create event sets
var eventSets = {}
var days = mainCalender.querySelectorAll('[role="gridcell"]')
days.forEach((day, index) => {
  var events = Array.from(day.querySelectorAll('[role="button"]'))
  events.forEach(event => {
    var eventKey = event.querySelector('div:nth-child(2)').textContent.replace(/\s+/g,'')
    eventKey = index + eventKey
    eventSets[eventKey] = eventSets[eventKey] || []
    eventSets[eventKey].push(event)
  })
})


Object.values(eventSets)
  .filter(events => events.length > 1)
  .forEach(events => {
  	// get colors
  	var colors = events.map(event => event.style.backgroundColor || event.style.borderColor)
  	var gradient = stripesGradient(colors)

  	var eventToKeep = events.shift()
    eventToKeep.style.backgroundImage = gradient

    // adjust width of keeping element
    // fixme: this adjustment does not work properly for all cases
    var width = Number(events[0].style.width.replace(/%/g, ''))
    if (!isNaN(width)) {
      width = width * (events.length + 1)
      width = Math.min(width, 100)
      eventToKeep.style.width = width + '%'
    }

    // hide others
    events.forEach(event => {
      event.style.visibility = 'hidden'
    })
  })
```

**Comment by kateschiffelbein** [comment]
@imightbeamy Is there any update on making this compatible with the new view? Love the plugin and want to be able to update our company's calendars to the new view.

**Comment by torzsmokus** [comment]
@tdudek this looked good to me … until I clicked on a striped event :(
thx though, keep up the good work :+1:

**Comment by morkro** [comment]
Unfortunately, @tdudek's script doesn't work for me. `textContent` of `null`. Is it possible that the markup differs for some user?

**Comment by torzsmokus** [comment]
@morkro which view are you using? monthly view did not work for me either

**Comment by morkro** [comment]
@torzsmokus In fact, it was the monthly view :) It does work with the other views.

**Comment by Beetlecat** [comment]
Not a nag, but a *best of luck* in getting this working with the new layout. Looks like Google pushed it out w/o and option to toggle back to "classic."

Thanks for the attention, everyone! :D

**Comment by djr7m** [comment]
@Beetlecat  they still have the option in the "gear" icon that says "Back to classic Calendar"... at least for me today.

**Comment by pkup10** [comment]
If you are a gsuite user your admin, I believe can force the change with no
opt out.

**Comment by ivancwc** [comment]
google calendar is reminding me to switch new UI whenever I go to the site :(

**Comment by mhtong** [comment]
Google forced the switch for me. Any update?

**Comment by torzsmokus** [comment]
@everybody please *stop* whining here. only comment if you can add something constructive (e.g. code for the new UI, even better a pull request). click _Subscribe_ in the right column instead, so you will get any updates. kthxbye

**Comment by alexmoss** [comment]
@tdudek is there a walkthrough on how to implement your copy-and-paste console code?

**Comment by aprince04** [comment]
The script above works on the new calendar! Yes!!!!
I will attempt a how-to:
* Copy the code above
* When viewing your calendar, click the three stacked dots top right of Chrome
* More Tools / developer
* This should split your screen with your calendar to the left and developer window to the right.
* In the developer window click Sources, Second row top left you might be looking at Network>file system - change file system to snippets.
* Click + New Snippet and give it a name
* Paste code in the window to the right
* (Option) save it - right click save as - for later retrieval
* Bottom right - what looks like a play button with Crtl+enter  - click the play icon it to run script.
* Your calendar events should be merged!

**Comment by OtterlyAdorable** [comment]
@aprince04   Can confirm, this worked for me!  Thank you!

**Comment by alexmoss** [comment]
Thanks! Worked for me, although would be great to run on every page reload instead of running manually each time.

**Comment by OtterlyAdorable** [comment]
@alexmoss Was just going to say the same thing.  Does anyone know if there is a way to make it automatically run?

**Comment by imightbeamy** [comment]
Hi all sorry for being very absent! If you look in the original extension, [you'll see it uses a "DOMNodeInserted" event to re-merge](https://github.com/imightbeamy/gcal-multical-event-merge/blob/master/events.user.js#L138). Would happily accept a PR that ran the above code on that event or similar!

**Comment by asvarga** [comment]
Slightly less tedious: drag the link from the output of this JSFiddle to your bookmarks bar and click it while in Google Calendar: https://jsfiddle.net/asvarga/q9pj91qg/3/

**Comment by fredley** [comment]
I have made a PR that puts this code in a simple `$(document).ready()` event. Adding it to other events should be straightforward, if we can find one that triggers when adding a new event, or the DOM is otherwise updated (the old update handlers don't work since the elements no longer have ids).

**Comment by alexmoss** [comment]
Please share @fredley :)

**Comment by fredley** [comment]
![](https://i.imgur.com/qEX0RJQ.png)

**Comment by imightbeamy** [comment]
Hi all, Thanks for the help getting this update going and sorry it too so long to get out! [An updated version has been released](https://github.com/imightbeamy/gcal-multical-event-merge/releases/tag/v2.0.0) and [uploaded in the Chrome store](https://chrome.google.com/webstore/detail/event-merge-for-google-ca/idehaflielbgpaokehlhidbjlehlfcep). I'm sure it will have it's fair share of bugs, so feel free to open new issues here for those. 

You can expect to see the new version over the next few hours. 

🥂,

-Amy

**Comment by beporter** [comment]
@imightbeamy I know I personally have gotten **years** of benefit from this Chrome extension. It has saved me from untold calendar-induced headaches. Do you perhaps have a PayPal link you'd be willing to share? Or maybe a favorite charity we could donate to if that's preferable?

**Comment by imightbeamy** [comment]
@beporter Yes! Thanks for asking. 

If you'd like to thank me for this extension send some support to the Defend J20 legal fund for protesters arrested at the inauguration last year. 59 defendants are still facing decades in prison 😔

Donate here: https://fundrazr.com/j20resistance

Learn more about the case here: http://defendj20resistance.org

**Comment by gregschwartz** [comment]
@imightbeamy thanks for the update! I just donated :)

**Comment by duckunix** [comment]
Chrome v65
Thanks for the update.  It is working, but some events disappear based on which calendars I have displayed.

So, I have two shared calendars with my wife, plus the Google family one, one shared with an organization I work with, and a couple of web sites.  Plus a few read-only calendar feeds.  And my wife uses custom color for events to track which kid the event is for.

If I turn off the wife's calendar, some events are visible, turn on, those events not be displayed.  They are only on one calendar, but have custom colors.  

If I turn off a different r/w calendar, then a different set of appointments appear/disappear. 

Short, the pattern seems to be that the update is causing events with custom colors to be not displayed.

**Comment by imightbeamy** [comment]
@duckunix thanks! I know it's a little buggy, I already started tracking down some weirdness. Could you open a new issue for what you're seeing?

**Comment by imightbeamy** [comment]
I've locked this convo since this now supports the new UI, open new issues for bugz! 🐛
