### ISSUE TITLE
Events with custom colors are merged regardless of the title/event time

### ISSUE THREAD

**Issue by duckunix** [imightbeamy/gcal-multical-event-merge#52]
Chrome v65
Thanks for the update. It is working, but some events disappear based on which calendars I have displayed.

So, I have two shared calendars with my wife, plus the Google family one, one shared with an organization I work with, and a couple of web sites. Plus a few read-only calendar feeds. And my wife uses custom color for events to track which kid the event is for.

If I turn off the wife's calendar, some events are visible, turn on, those events not be displayed. They are only on one calendar, but have custom colors.

If I turn off a different r/w calendar, then a different set of appointments appear/disappear.

Short, the pattern seems to be that the update is causing events with custom colors to be not displayed.

**Comment by imightbeamy** [comment]
There's def some issues with custom colors 🤔 

It looks like all events with custom colors are getting merged regardless of the time of day and title:
![screen shot 2018-02-17 at 10 39 36 pm](https://user-images.githubusercontent.com/1229145/36347953-86aaf58e-1433-11e8-8a7e-9d5ba65b70f5.png)![screen shot 2018-02-17 at 10 39 46 pm](https://user-images.githubusercontent.com/1229145/36347952-869cba0a-1433-11e8-94cb-627277df4886.png)

**Comment by duckunix** [comment]
ah...good find.  BTW - like the title.  It is much better. :)

**Comment by imightbeamy** [comment]
Just uploaded a [new version](https://github.com/imightbeamy/gcal-multical-event-merge/releases/tag/v2.1.1) that should have this issue fixed! 

You should get the update over a few hours. If you're in a hurry, you can go to `chrome://extensions/`, check "Developer Mode" and click "Update extensions now":
![screen shot 2018-02-18 at 9 06 49 am](https://user-images.githubusercontent.com/1229145/36352722-48a7320e-148b-11e8-8fcb-ab1f7f3ef7f9.png)

**Comment by duckunix** [comment]
Much better...not hiding events, but I still have a pair of events which are on two calendars, but the second calendar has a custom color, and they are not merging.  New issue?

**Comment by imightbeamy** [comment]
Ah yeah, seeing that! [I think this should fix it.](https://github.com/imightbeamy/gcal-multical-event-merge/commit/cc0637e2bc976f141e7dfbc06ed35975543e3d05) I'll make a new release later today!
