### ISSUE TITLE
Plugin requests additional permission: read browsing history

### ISSUE THREAD

**Issue by eilamg** [imightbeamy/gcal-multical-event-merge#53]
Hey

Chrome (64.0.3282.167) just disabled the plugin, notifying me that Event Merge now requires an additional permission to "Read your browsing history".

Didn't see this mentioned on the webstore page and was wondering why the added requirement?

Cheers,
Eilam

**Comment by imightbeamy** [comment]
Hmmmm, I did add a "tabs" permission to allow the pull-on to refresh calendar tabs when toggled, but it's weird that it would call that "browser history"

Assuming it is the tab permission doing it, I'll look for another way to do the refresh.

Thanks for pointing this out!

**Comment by imightbeamy** [comment]
Just uploaded a [new version](https://github.com/imightbeamy/gcal-multical-event-merge/releases/tag/v2.1.1), [sans "tabs" permissions](https://github.com/imightbeamy/gcal-multical-event-merge/commit/93a3b7a1a311f41eb41d48665ef49d11afabbb54)

You should get the update over a few hours. If you're in a hurry, you can go to `chrome://extensions/`, check "Developer Mode" and click "Update extensions now":
![screen shot 2018-02-18 at 9 06 49 am](https://user-images.githubusercontent.com/1229145/36352722-48a7320e-148b-11e8-8fcb-ab1f7f3ef7f9.png)
