### ISSUE TITLE
`background-image` bug when ticking "MAYBE"

### ISSUE THREAD

**Issue by nirazul** [imightbeamy/gcal-multical-event-merge#57]
When setting the event invitation to "maybe" some CSS styles get messed up.
From a technical point of view, there's a `background-size` property written on the event. This mixes with the stripes from the plugin:

![dreipol_gmbh_ _calendar_-_week_of_19_march_2018_](https://user-images.githubusercontent.com/781476/36541840-7f5e05f0-17df-11e8-9186-de8f9577d13b.jpg)

![developer_tools_-_https___calendar_google_com_calendar_r_week_2018_3_22](https://user-images.githubusercontent.com/781476/36542068-13aec0f0-17e0-11e8-8630-78ba1e62339a.jpg)

Without the plugin it looks like this:
![dreipol_gmbh_ _calendar_-_week_of_19_march_2018_](https://user-images.githubusercontent.com/781476/36542384-f4ece010-17e0-11e8-9acd-334b93be74fe.jpg)

**Comment by imightbeamy** [comment]
Oooh, I've been noticing that too. This should be a pretty quick one to fix if you have time to whip up a a PR. You'll need to set background size to null/undefined where the striped background gets set, and add it to the "original styles" so it gets reset if the event is no longer in a merge set.

**Comment by Nirazul** [comment]
I'll try to squeeze it in this or the next week. If anybody feels like tackling this before, feel free!
