### ISSUE TITLE
Dragging events moves my event rather than owner's

### ISSUE THREAD

**Issue by eshear** [imightbeamy/gcal-multical-event-merge#6]
This is my favorite extension right now. Great work.

This request is based around a common workflow:

* Someone else has invited me to an event and I have to reschedule
* I open up both of our calendars so that I can move it, and the extension nicely collapses everything with stripes
* I see an open spot for both of us on another and drag the event into it

The problem is that I get "the changes you will be making will only be reflected in the calendar of YOUR NAME" because I'm dragging my event. This is because when I'm dragging the merged event, I'm dragging the copy on my calendar and I don't own the event. 

Ideally the event would be the copy owned by the other person. Instead, I have to turn off my own calendar and then move the event because it's otherwise inaccessible (due to the merge).

**Comment by imightbeamy** [comment]
Hey @eshear, 

Thanks for the report. I hope the extension is still working out for you!

Unfortunately there are a lot of limitations that come with this being an extension. There's really no way to tell which copy of the event is the the "owners" without add a ton of complication (I'm talking like, using the google cal API or something). While I know it's not ideal, I think the only option right now it to turn off your calendar, move the event, and turn your calendar back on.

If I ever come up with a way to fix it I will :)
