### ISSUE TITLE
Doesn't seem to be working in new UI for me

### ISSUE THREAD

**Issue by beaugunderson** [imightbeamy/gcal-multical-event-merge#62]
![screenshot](https://i.imgur.com/813Qqf4.png)

let me know if there's any way I can help debug; this would make my calendar way more usable!

**Comment by mboyajian-gcp** [comment]
not working for me either, hopefully it gets fixed soon!

**Comment by jjeaton** [comment]
Same here. Although I'm pretty sure this was working as recently as last week for me.

**Comment by torzsmokus** [comment]
same for me, but it still works for Out-of-Office events :open_mouth: 
![image](https://user-images.githubusercontent.com/641862/44804631-2eae9a80-abc2-11e8-9554-2c2ccdd50554.png)

**Comment by mboyajian-gcp** [comment]
still not working for me. (OSX, Chrome Version 69.0.3497.100, Official Build, 64-bit)

**Comment by torzsmokus** [comment]
it is already OK for me (Ubuntu Chrome 69.0.3497.100, Official Build, 64-bit)

**Comment by da4throux** [comment]
Not working for me too (Chromebook, Version 69.0.3497.120 (Official Build) (64-bit) )
No error in the console.
Anything I can provide / test to help ?

**Comment by imightbeamy** [comment]
Seems like it's working for some as these reports are old. If it's still not working open a new issue!
