### ISSUE TITLE
Random text colours in event titles (new Google Calendar)

### ISSUE THREAD

**Issue by tiatiara** [imightbeamy/gcal-multical-event-merge#63]
Hello

I'm a big fan of this extension but I'm having issues with the Event Titles taking on seemingly random colours. This didn't happen in the previous Google Calendar, only since the update.

There doesn't seem to be any logic to the colour application – sometimes it's white and sometimes it takes on a particular calendar's colour swatch (see screenshot). Another strange thing is that when I click on the Event Title it sometimes the colour of the text and/or colour bands.

From memory, when I used this extension with the original Google Calendar, the text was only ever white or black. This made it relatively easy to choose appropriate colours. Any advice would be fantastic.

<img width="47" alt="screen shot 2018-09-06 at 7 47 48 am" src="https://user-images.githubusercontent.com/20064435/45123145-43ce8f00-b1a9-11e8-9e9c-ad1b1a1d7178.png">

**Comment by imightbeamy** [comment]
I've been seeing this too, sorry for the slow reply! I think it has to do with people replying "maybe" 🤔 I'll try to look when I can!
