### ISSUE TITLE
Events bleed into previous day in new gcal view

### ISSUE THREAD

**Issue by danamarsh** [imightbeamy/gcal-multical-event-merge#67]
<img width="319" alt="banners_and_alerts_and_jobber_-_calendar_-_7_days__starting_monday__december_17__2018" src="https://user-images.githubusercontent.com/40809450/50118190-2f6c4a80-020c-11e9-88ce-477b9670b139.png">
In 7-day view, as of Dec 17, merged events bleed into the previous day. Issue resolves when you toggle out of merge-view, but that defeats the purpose of the plug-in. :)

**Comment by danamarsh** [comment]
<img width="343" alt="jobber_-_calendar_-_7_days__starting_monday__december_17__2018" src="https://user-images.githubusercontent.com/40809450/50119046-c2a67f80-020e-11e9-9c36-373ec5dbfd0f.png">
And weirdly, the bleed gets worse the longer the page is open...

**Comment by michaelblyons** [comment]
FWIW, I do not toggle in and out, but I also see this behaviour. This morning, the events were spread all the way to the left side of the screen. 😆
