### ISSUE TITLE
Case insensitive

### ISSUE THREAD

**Issue by themacmarketer** [imightbeamy/gcal-multical-event-merge#68]
Hello,

Is the merging case sensitive?
e.g. "EVENT A" and "Event A" will not be merged.

If so can anyone please advise how I could make it case insensitive?

Thank you.

Ivan

**Comment by imightbeamy** [comment]
Yes, merging is case sensitive. Right now there's no way to change that! Best I can recommend is to re-name the events to be the same 😅
