### ISSUE TITLE
Option to have title on solid background while the remainder is still striped.

### ISSUE THREAD

**Issue by dpieski** [imightbeamy/gcal-multical-event-merge#73]
Is there a way to have the text on a solid background but have the stripes around it still?

For some color combos it is very difficult to read the text. 

![image](https://user-images.githubusercontent.com/3300522/57248792-e37a4080-7008-11e9-862d-a2284a2c48ad.png)

to something like:

![image](https://user-images.githubusercontent.com/3300522/57248905-3522cb00-7009-11e9-8ead-c6b94bd427ae.png)

With the number of people I have on the calendar, simple changing the color is not an option. Trying to find a color that is not already in use is time consuming with our setup. Additionally, I am considering suggesting this to the company I work for. Having everyone change the colors that make it hard to read is a lot of business time.

Thanks!

**Comment by thesebas** [comment]
I would opt for adding shadow `text-shadow: {$contrast_colour} 0px 0px 5px;`

**Comment by imightbeamy** [comment]
I've merged @thesebas's change which helps with this issue. Thanks all!
