### ISSUE TITLE
Sometimes a merged event crosses into the next day (in week view)

### ISSUE THREAD

**Issue by danielmendel** [imightbeamy/gcal-multical-event-merge#9]
Here is with the extension turned on:
![screen shot 2015-03-16 at 5 12 53 pm](https://cloud.githubusercontent.com/assets/304202/6676664/0bdc7004-cc00-11e4-97a6-005152079229.png)

And here it is off:
![screen shot 2015-03-16 at 5 13 45 pm](https://cloud.githubusercontent.com/assets/304202/6676663/0bdb2d7a-cc00-11e4-84a7-302c15b1dcf0.png)

**Comment by imightbeamy** [comment]
Seems to be a problem with < half hour long events, and events with long titles without spaces.

Half hour event:
![screen shot 2015-03-16 at 5 17 51 pm](https://cloud.githubusercontent.com/assets/1229145/6676729/7e8358ca-cc00-11e4-8735-e7ca61e161ed.png)

Same event 1 hour long:
![screen shot 2015-03-16 at 5 18 01 pm](https://cloud.githubusercontent.com/assets/1229145/6676730/7e8457e8-cc00-11e4-87a3-d3f65fef261e.png)

Same event without spaces:
![screen shot 2015-03-16 at 5 20 35 pm](https://cloud.githubusercontent.com/assets/1229145/6676786/e1619c2c-cc00-11e4-8e61-0d6b0e4e7eae.png)

I'll try to get it fixed up asap. Thanks @danielmendel! :+1:
